package lang

import (
	"fmt"
	"path/filepath"
	"strings"
)

// Express / Node builder. Emits numbered SQL migrations (run by the scaffold's
// idempotent migration runner), TS row-shape models, and auto-mounted CRUD routers
// that use the scaffold-owned `pool` from ../db. Migration numbers start at 010
// (auth owns 000_; the model's own custom migrations use 900+).

func init() {
	b := &Builder{
		Framework:  "express",
		Migrations: expressMigrations,
		Models:     expressModels,
		Routes:     expressRoutes,
	}
	registerBuilder(b)
	// Generic Node scaffold shares the Express skeleton (db.ts/migrate.ts/auto-mount).
	nodeCopy := *b
	nodeCopy.Framework = "node"
	registerBuilder(&nodeCopy)
}

func expressMigrations(spec BuildSpec) []GenFile {
	ordered := orderByFK(spec.Entities)
	var files []GenFile
	for i, e := range ordered {
		num := fmt.Sprintf("%03d", 10+i)
		files = append(files, GenFile{
			Path:    filepath.Join("migrations", num+"_"+e.Table+".sql"),
			Content: expressMigrationSQL(e),
		})
	}
	return files
}

func expressMigrationSQL(e BuildEntity) string {
	var b strings.Builder
	fmt.Fprintf(&b, "-- %s: generated by the API builder. The migration runner is idempotent; safe to extend.\n", e.Table)
	fmt.Fprintf(&b, "CREATE TABLE IF NOT EXISTS %s (\n", e.Table)
	b.WriteString("  id SERIAL PRIMARY KEY")
	for _, f := range e.Fields {
		line := "  " + f.Name + " " + pgType(f.Type)
		if !f.Nullable {
			line += " NOT NULL"
		}
		if f.Unique {
			line += " UNIQUE"
		}
		if f.Default != "" {
			line += " DEFAULT " + f.Default
		}
		if f.Ref != "" {
			rt, rc := refTarget(f.Ref)
			line += fmt.Sprintf(" REFERENCES %s(%s) ON DELETE CASCADE", rt, rc)
		}
		b.WriteString(",\n" + line)
	}
	b.WriteString(",\n  created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n);\n")
	for _, f := range e.Fields {
		if f.Index || f.Ref != "" {
			fmt.Fprintf(&b, "CREATE INDEX IF NOT EXISTS idx_%s_%s ON %s(%s);\n", e.Table, f.Name, e.Table, f.Name)
		}
	}
	return b.String()
}

func expressModels(spec BuildSpec) []GenFile {
	var files []GenFile
	for _, e := range spec.Entities {
		files = append(files, GenFile{
			Path:    filepath.Join("src", "models", e.Name+".ts"),
			Content: expressModelTS(e),
		})
	}
	return files
}

func expressModelTS(e BuildEntity) string {
	tn := title(e.Name)
	var b strings.Builder
	fmt.Fprintf(&b, "// %s row shape, generated from the data model.\n", tn)
	fmt.Fprintf(&b, "export interface %s {\n  id: number;\n", tn)
	for _, f := range e.Fields {
		null := ""
		if f.Nullable {
			null = " | null"
		}
		fmt.Fprintf(&b, "  %s: %s%s;\n", f.Name, tsFieldType(f.Type), null)
	}
	b.WriteString("  created_at: string;\n}\n\n")
	fmt.Fprintf(&b, "// Fields accepted when creating a %s.\n", e.Name)
	fmt.Fprintf(&b, "export interface New%s {\n", tn)
	for _, f := range e.Fields {
		opt := ""
		if f.Nullable {
			opt = "?"
		}
		fmt.Fprintf(&b, "  %s%s: %s;\n", f.Name, opt, tsFieldType(f.Type))
	}
	b.WriteString("}\n")
	return b.String()
}

func expressRoutes(spec BuildSpec) ([]GenFile, []string) {
	var files []GenFile
	var blanks []string
	for _, e := range spec.Entities {
		content := expressRouteTS(e, tableNeedsAuth(spec, e.Table))
		files = append(files, GenFile{
			Path:    filepath.Join("src", "routes", e.Table+".ts"),
			Content: content,
		})
		blanks = append(blanks, fmt.Sprintf("backend/src/routes/%s.ts — list/get/create/update/delete for %s (fill each LOGIC block)", e.Table, e.Name))
	}
	return files, blanks
}

func tableNeedsAuth(spec BuildSpec, table string) bool {
	for _, ep := range spec.Endpoints {
		if ep.Auth && strings.Contains(ep.Path, "/"+table) {
			return true
		}
	}
	return false
}

func expressRouteTS(e BuildEntity, auth bool) string {
	t := e.Table
	guard, authImport := "", ""
	if auth {
		authImport = "import { requireAuth } from '../auth';\n"
		guard = "requireAuth, "
	}

	var cols []string
	for _, f := range e.Fields {
		cols = append(cols, f.Name)
	}
	destr := strings.Join(cols, ", ")
	var ph, sets []string
	for i, c := range cols {
		ph = append(ph, fmt.Sprintf("$%d", i+1))
		sets = append(sets, fmt.Sprintf("%s = $%d", c, i+1))
	}

	var b strings.Builder
	b.WriteString("import { Router } from 'express';\n")
	b.WriteString("import { pool } from '../db';\n")
	b.WriteString(authImport)
	b.WriteString("\n")
	fmt.Fprintf(&b, "// Auto-mounted at /api/%s. CRUD for %s. Fill ONLY the code inside each marked\n", t, e.Name)
	b.WriteString("// LOGIC block (between its open and close comment); leave everything else as-is.\n")
	b.WriteString("const router = Router();\n\n")

	// LIST
	fmt.Fprintf(&b, "router.get('/', %sasync (req, res) => {\n", guard)
	fmt.Fprintf(&b, "  // === LOGIC:list %s ===\n", t)
	b.WriteString("  // Returns all rows. Add filtering / sorting / pagination / ownership scoping here.\n")
	b.WriteString("  try {\n")
	fmt.Fprintf(&b, "    const { rows } = await pool.query('SELECT * FROM %s ORDER BY id DESC');\n", t)
	b.WriteString("    res.json(rows);\n")
	b.WriteString("  } catch (err) { res.status(500).json({ error: (err as Error).message }); }\n")
	b.WriteString("  // === END LOGIC ===\n});\n\n")

	// GET :id
	fmt.Fprintf(&b, "router.get('/:id', %sasync (req, res) => {\n", guard)
	fmt.Fprintf(&b, "  // === LOGIC:get %s ===\n", e.Name)
	b.WriteString("  try {\n")
	fmt.Fprintf(&b, "    const { rows } = await pool.query('SELECT * FROM %s WHERE id = $1', [req.params.id]);\n", t)
	b.WriteString("    if (rows.length === 0) return res.status(404).json({ error: 'not found' });\n")
	b.WriteString("    res.json(rows[0]);\n")
	b.WriteString("  } catch (err) { res.status(500).json({ error: (err as Error).message }); }\n")
	b.WriteString("  // === END LOGIC ===\n});\n\n")

	// POST
	fmt.Fprintf(&b, "router.post('/', %sasync (req, res) => {\n", guard)
	fmt.Fprintf(&b, "  // === LOGIC:create %s ===\n", e.Name)
	b.WriteString("  // Validate input and set any owner_id/user_id from the authed user here.\n")
	b.WriteString("  try {\n")
	if len(cols) == 0 {
		fmt.Fprintf(&b, "    const { rows } = await pool.query('INSERT INTO %s DEFAULT VALUES RETURNING *');\n", t)
	} else {
		fmt.Fprintf(&b, "    const { %s } = req.body;\n", destr)
		fmt.Fprintf(&b, "    const { rows } = await pool.query(\n")
		fmt.Fprintf(&b, "      'INSERT INTO %s (%s) VALUES (%s) RETURNING *',\n", t, destr, strings.Join(ph, ", "))
		fmt.Fprintf(&b, "      [%s]\n    );\n", destr)
	}
	b.WriteString("    res.status(201).json(rows[0]);\n")
	b.WriteString("  } catch (err) { res.status(500).json({ error: (err as Error).message }); }\n")
	b.WriteString("  // === END LOGIC ===\n});\n\n")

	// PUT :id
	fmt.Fprintf(&b, "router.put('/:id', %sasync (req, res) => {\n", guard)
	fmt.Fprintf(&b, "  // === LOGIC:update %s ===\n", e.Name)
	b.WriteString("  try {\n")
	if len(cols) == 0 {
		fmt.Fprintf(&b, "    const { rows } = await pool.query('SELECT * FROM %s WHERE id = $1', [req.params.id]);\n", t)
	} else {
		fmt.Fprintf(&b, "    const { %s } = req.body;\n", destr)
		fmt.Fprintf(&b, "    const { rows } = await pool.query(\n")
		fmt.Fprintf(&b, "      'UPDATE %s SET %s WHERE id = $%d RETURNING *',\n", t, strings.Join(sets, ", "), len(cols)+1)
		fmt.Fprintf(&b, "      [%s, req.params.id]\n    );\n", destr)
	}
	b.WriteString("    if (rows.length === 0) return res.status(404).json({ error: 'not found' });\n")
	b.WriteString("    res.json(rows[0]);\n")
	b.WriteString("  } catch (err) { res.status(500).json({ error: (err as Error).message }); }\n")
	b.WriteString("  // === END LOGIC ===\n});\n\n")

	// DELETE :id
	fmt.Fprintf(&b, "router.delete('/:id', %sasync (req, res) => {\n", guard)
	fmt.Fprintf(&b, "  // === LOGIC:delete %s ===\n", e.Name)
	b.WriteString("  try {\n")
	fmt.Fprintf(&b, "    await pool.query('DELETE FROM %s WHERE id = $1', [req.params.id]);\n", t)
	b.WriteString("    res.status(204).end();\n")
	b.WriteString("  } catch (err) { res.status(500).json({ error: (err as Error).message }); }\n")
	b.WriteString("  // === END LOGIC ===\n});\n\n")

	b.WriteString("export default router;\n")
	return b.String()
}
